import json
import logging
import os
import requests
from django.conf import settings
from django.core.files.storage import default_storage
from django.db import transaction
from decouple import config
from rest_framework import viewsets, permissions, status
from rest_framework.decorators import action
from rest_framework.response import Response

import pypdf

from resources.models import Resource
from .models import GeneratedQuiz, QuizQuestion, QuizAttempt
from .serializers import GeneratedQuizSerializer, QuizAttemptSerializer

logger = logging.getLogger(__name__)


def extract_text_from_pdf(file_path_or_file):
    """
    Extracts text from a PDF file using pypdf.
    Supports file path (string) or file-like object.
    """
    text = ""
    try:
        reader = pypdf.PdfReader(file_path_or_file)
        for page in reader.pages:
            page_text = page.extract_text()
            if page_text:
                text += page_text + "\n"
    except Exception as e:
        logger.error(f"Error extracting PDF text: {str(e)}")
        raise ValueError(f"Failed to read PDF file: {str(e)}")
    return text


def extract_text_from_txt(file_obj):
    """
    Extracts text from a plain text file.
    """
    try:
        content = file_obj.read()
        if isinstance(content, bytes):
            return content.decode('utf-8', errors='ignore')
        return content
    except Exception as e:
        logger.error(f"Error extracting TXT text: {str(e)}")
        raise ValueError(f"Failed to read text file: {str(e)}")


class QuizViewSet(viewsets.ModelViewSet):
    serializer_class = GeneratedQuizSerializer
    permission_classes = [permissions.IsAuthenticated]

    def get_queryset(self):
        # Only return quizzes generated by the current user
        return GeneratedQuiz.objects.filter(created_by=self.request.user)

    def perform_create(self, serializer):
        serializer.save(created_by=self.request.user)

    @action(detail=False, methods=['post'], url_path='generate')
    def generate_quiz(self, request):
        user = request.user
        num_questions = int(request.data.get('num_questions', 5))
        difficulty = request.data.get('difficulty', 'Medium')
        
        # Limit question range for stability and token limits
        if num_questions < 1 or num_questions > 15:
            return Response({'error': 'Number of questions must be between 1 and 15.'}, status=status.HTTP_400_BAD_REQUEST)

        # 1. Source notes text
        notes_text = ""
        source_resource = None

        # Scenario A: Pasted Text content
        text_content = request.data.get('text_content', '').strip()
        
        # Scenario B: Uploaded file
        uploaded_file = request.FILES.get('file')

        # Scenario C: Existing Resource
        resource_id = request.data.get('resource_id')

        use_multimodal_file = False
        multimodal_file_data = None
        multimodal_file_mime = None

        if text_content:
            notes_text = text_content
        elif uploaded_file:
            ext = uploaded_file.name.split('.')[-1].lower()
            if ext == 'pdf':
                try:
                    notes_text = extract_text_from_pdf(uploaded_file)
                except Exception as e:
                    logger.warning(f"PDF text extraction failed: {str(e)}")
                    notes_text = ""
                
                # If text is empty or too short, fallback to sending PDF bytes directly to Gemini
                if len(notes_text.strip()) < 100:
                    use_multimodal_file = True
                    uploaded_file.seek(0)
                    file_bytes = uploaded_file.read()
                    import base64
                    multimodal_file_data = base64.b64encode(file_bytes).decode('utf-8')
                    multimodal_file_mime = "application/pdf"
            elif ext in ['png', 'jpg', 'jpeg']:
                use_multimodal_file = True
                uploaded_file.seek(0)
                file_bytes = uploaded_file.read()
                import base64
                multimodal_file_data = base64.b64encode(file_bytes).decode('utf-8')
                multimodal_file_mime = f"image/{'jpeg' if ext == 'jpg' else ext}"
            elif ext in ['txt', 'md']:
                notes_text = extract_text_from_txt(uploaded_file)
            else:
                return Response({'error': 'Unsupported file type. Supported types are PDF, Images (PNG/JPG), and TXT/MD.'}, status=status.HTTP_400_BAD_REQUEST)
        elif resource_id:
            try:
                source_resource = Resource.objects.get(id=resource_id)
                file_url = source_resource.file.url
                ext = source_resource.file.name.split('.')[-1].lower()
                
                # Try downloading or reading it
                if hasattr(source_resource.file, 'path') and os.path.exists(source_resource.file.path):
                    # Local file storage
                    if ext == 'pdf':
                        try:
                            notes_text = extract_text_from_pdf(source_resource.file.path)
                        except Exception as e:
                            logger.warning(f"Local PDF extraction failed: {str(e)}")
                            notes_text = ""
                        
                        if len(notes_text.strip()) < 100:
                            use_multimodal_file = True
                            with open(source_resource.file.path, 'rb') as f:
                                file_bytes = f.read()
                            import base64
                            multimodal_file_data = base64.b64encode(file_bytes).decode('utf-8')
                            multimodal_file_mime = "application/pdf"
                    elif ext in ['png', 'jpg', 'jpeg']:
                        use_multimodal_file = True
                        with open(source_resource.file.path, 'rb') as f:
                            file_bytes = f.read()
                        import base64
                        multimodal_file_data = base64.b64encode(file_bytes).decode('utf-8')
                        multimodal_file_mime = f"image/{'jpeg' if ext == 'jpg' else ext}"
                    else:
                        with open(source_resource.file.path, 'rb') as f:
                            notes_text = extract_text_from_txt(f)
                else:
                    # Cloud storage (Cloudinary) or remote
                    if not file_url.startswith('http'):
                        file_url = request.build_absolute_uri(file_url)
                    
                    response = requests.get(file_url, stream=True)
                    if response.status_code == 200:
                        from io import BytesIO
                        file_bytes = BytesIO(response.content)
                        if ext == 'pdf':
                            try:
                                notes_text = extract_text_from_pdf(file_bytes)
                            except Exception as e:
                                logger.warning(f"Remote PDF extraction failed: {str(e)}")
                                notes_text = ""
                            
                            if len(notes_text.strip()) < 100:
                                use_multimodal_file = True
                                file_bytes.seek(0)
                                import base64
                                multimodal_file_data = base64.b64encode(file_bytes.read()).decode('utf-8')
                                multimodal_file_mime = "application/pdf"
                        elif ext in ['png', 'jpg', 'jpeg']:
                            use_multimodal_file = True
                            file_bytes.seek(0)
                            import base64
                            multimodal_file_data = base64.b64encode(file_bytes.read()).decode('utf-8')
                            multimodal_file_mime = f"image/{'jpeg' if ext == 'jpg' else ext}"
                        else:
                            notes_text = extract_text_from_txt(file_bytes)
                    else:
                        return Response({'error': 'Could not retrieve notes file from cloud storage.'}, status=status.HTTP_400_BAD_REQUEST)
            except Resource.DoesNotExist:
                return Response({'error': 'Selected resource does not exist.'}, status=status.HTTP_404_NOT_FOUND)
            except Exception as e:
                return Response({'error': f'Failed to process selected resource: {str(e)}'}, status=status.HTTP_400_BAD_REQUEST)
        else:
            return Response({'error': 'Please provide text, upload a file, or select a resource.'}, status=status.HTTP_400_BAD_REQUEST)

        # Clean notes text and check length (only if not multimodal file input)
        if not use_multimodal_file:
            notes_text = notes_text.strip()
            if len(notes_text) < 50:
                return Response({'error': 'The provided study material is too short or empty. Please provide at least 50 characters.'}, status=status.HTTP_400_BAD_REQUEST)

        # 2. Query Gemini API
        api_key = config('GEMINI_API_KEY', default=None)
        if not api_key:
            return Response({
                'error': 'Gemini API Key is not configured. Please add GEMINI_API_KEY to backend/.env'
            }, status=status.HTTP_500_INTERNAL_SERVER_ERROR)

        gemini_url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key={api_key}"
        
        # System prompt instructions - upgraded for professional university standards
        prompt_text = (
            f"You are a professional university professor and academic expert. Analyze the provided study material carefully. "
            f"If the material contains handwritten notes, scans, or diagrams, transcribe and interpret them accurately. "
            f"Generate a high-quality, professional academic quiz with exactly {num_questions} multiple-choice questions (MCQs) "
            f"of {difficulty} difficulty based on the concepts. The questions must test conceptual understanding, critical thinking, "
            f"and application of knowledge, not just simple rote memorization.\n\n"
            f"For each question:\n"
            f"- Formulate a clear, grammatically correct, and professional question text.\n"
            f"- Create 4 distinct, plausible options (A, B, C, D) where only one is unambiguously correct and the others are realistic distractors. Avoid obvious fillers or 'all of the above' options.\n"
            f"- Identify the correct_answer (must be one of 'A', 'B', 'C', 'D').\n"
            f"- Write a comprehensive, clear academic explanation explaining why the correct option is right and why the other distractors are wrong."
        )

        parts = [
            {"text": prompt_text}
        ]

        if use_multimodal_file:
            parts.append({
                "inlineData": {
                    "mimeType": multimodal_file_mime,
                    "data": multimodal_file_data
                }
            })
        else:
            parts.append({
                "text": f"Note content:\n\n{notes_text[:20000]}" # truncate text to 20k characters to prevent token limits
            })

        schema = {
            "type": "OBJECT",
            "properties": {
                "title": {"type": "STRING"},
                "questions": {
                    "type": "ARRAY",
                    "items": {
                        "type": "OBJECT",
                        "properties": {
                            "question": {"type": "STRING"},
                            "option_a": {"type": "STRING"},
                            "option_b": {"type": "STRING"},
                            "option_c": {"type": "STRING"},
                            "option_d": {"type": "STRING"},
                            "correct_answer": {"type": "STRING", "enum": ["A", "B", "C", "D"]},
                            "explanation": {"type": "STRING"}
                        },
                        "required": ["question", "option_a", "option_b", "option_c", "option_d", "correct_answer", "explanation"]
                    }
                }
            },
            "required": ["title", "questions"]
        }

        payload = {
            "contents": [
                {
                    "parts": parts
                }
            ],
            "generationConfig": {
                "responseMimeType": "application/json",
                "responseSchema": schema
            }
        }

        try:
            res = requests.post(gemini_url, json=payload, headers={'Content-Type': 'application/json'}, timeout=60)
            if res.status_code != 200:
                logger.error(f"Gemini API returned code {res.status_code}: {res.text}")
                return Response({'error': f'Gemini API Error: {res.text}'}, status=status.HTTP_502_BAD_GATEWAY)

            res_json = res.json()
            candidates = res_json.get('candidates', [])
            if not candidates:
                return Response({'error': 'No response generated by Gemini AI.'}, status=status.HTTP_502_BAD_GATEWAY)
            
            content_text = candidates[0].get('content', {}).get('parts', [{}])[0].get('text', '{}')
            quiz_data = json.loads(content_text)
        except Exception as e:
            logger.error(f"Error communicating with Gemini: {str(e)}")
            return Response({'error': f'Failed to generate quiz: {str(e)}'}, status=status.HTTP_502_BAD_GATEWAY)

        # 3. Save to database
        try:
            with transaction.atomic():
                title_val = quiz_data.get('title') or f"Quiz on {difficulty} level"
                generated_quiz = GeneratedQuiz.objects.create(
                    title=title_val,
                    created_by=user,
                    resource=source_resource
                )
                
                questions_to_create = []
                for q in quiz_data.get('questions', []):
                    questions_to_create.append(QuizQuestion(
                        quiz=generated_quiz,
                        question_text=q.get('question', ''),
                        option_a=q.get('option_a', ''),
                        option_b=q.get('option_b', ''),
                        option_c=q.get('option_c', ''),
                        option_d=q.get('option_d', ''),
                        correct_answer=q.get('correct_answer', 'A'),
                        explanation=q.get('explanation', '')
                    ))
                
                QuizQuestion.objects.bulk_create(questions_to_create)
            
            # Return serialized quiz
            serializer = self.get_serializer(generated_quiz)
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        except Exception as e:
            logger.error(f"Database error saving quiz: {str(e)}")
            return Response({'error': f'Database save error: {str(e)}'}, status=status.HTTP_500_INTERNAL_SERVER_ERROR)

    @action(detail=True, methods=['post'], url_path='submit')
    def submit_answers(self, request, pk=None):
        quiz = self.get_object()
        user = request.user
        answers = request.data.get('answers', {}) # format: {question_id: 'A'/'B'/'C'/'D'}

        questions = quiz.questions.all()
        total_questions = questions.count()
        if total_questions == 0:
            return Response({'error': 'This quiz has no questions.'}, status=status.HTTP_400_BAD_REQUEST)

        score = 0
        results = []

        for q in questions:
            user_ans = answers.get(str(q.id)) or answers.get(q.id)
            is_correct = False
            if user_ans and user_ans.strip().upper() == q.correct_answer.upper():
                score += 1
                is_correct = True
            
            results.append({
                'question_id': q.id,
                'user_answer': user_ans,
                'correct_answer': q.correct_answer,
                'is_correct': is_correct,
                'explanation': q.explanation
            })

        # Save Attempt
        attempt = QuizAttempt.objects.create(
            quiz=quiz,
            user=user,
            score=score,
            total_questions=total_questions
        )

        # Gamification: Reward user with points (+2 points per correct answer)
        points_awarded = score * 2
        user.points += points_awarded
        user.save(update_fields=['points'])

        return Response({
            'attempt_id': attempt.id,
            'score': score,
            'total_questions': total_questions,
            'points_awarded': points_awarded,
            'new_total_points': user.points,
            'results': results
        }, status=status.HTTP_200_OK)


class AttemptViewSet(viewsets.ReadOnlyModelViewSet):
    serializer_class = QuizAttemptSerializer
    permission_classes = [permissions.IsAuthenticated]

    def get_queryset(self):
        # Only return attempts made by the current user
        return QuizAttempt.objects.filter(user=self.request.user)
