# Generated by Django 6.0.1 on 2026-05-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('file', models.FileField(upload_to='resources/')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('doc', 'Document (Word/Writer)'), ('image', 'Image'), ('ppt', 'PowerPoint'), ('other', 'Other')], default='other', max_length=10)),
                ('subject', models.CharField(max_length=100)),
                ('branch', models.CharField(choices=[('CSE', 'Computer Science and Engineering'), ('IT', 'Information Technology'), ('ECE', 'Electronics and Communication Engineering'), ('MECH', 'Mechanical Engineering'), ('CIVIL', 'Civil Engineering')], max_length=10)),
                ('semester', models.IntegerField()),
                ('tags', models.CharField(blank=True, default='', help_text='Comma-separated tags', max_length=255)),
                ('downloads', models.IntegerField(default=0)),
                ('avg_rating', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
