# Generated by Django 6.0.5 on 2026-06-07 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_emailotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='university',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
