# Generated by Django 6.0.5 on 2026-06-07 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_approved_faculty',
            field=models.BooleanField(default=False),
        ),
    ]
